### ISSUE TITLE
在 r3c.cpp 中 zrangebyscore 的实现 min 和 max 值的传递弄反了。

### ISSUE THREAD

**Issue by lsgxeva** [eyjian/r3c#12]
在 1670 行 : CRedisClient::zrangebyscore 的实现中, 
应该修改 const std::string str1 = any2string(min); const std::string str2 = any2string(max);

在 1692 行 : CRedisClient::zrevrangebyscore 的实现中, 
应该修改 const std::string str1 = any2string(min); const std::string str2 = any2string(max);

**Comment by eyjian** [comment]
谢谢！请再看看，最近做了重构，采用了新的实现，核心代码仍然是redis_command，相比上一版本逻辑上会清晰简单些，基于redis_command的各命令实现也自然了些，另外追加了一些单元测试用例，但还未完全覆盖到所有函数。valgrind检查结果干净，仍然不支持从读，但已考虑，计划下一版本加入这个特性。优化了CRedisException的实现，可以直接取到redis返回的错误类型了和原始的错误信息了。
