### ISSUE TITLE
require for transaction commands

### ISSUE THREAD

**Issue by spsoft** [eyjian/r3c#2]
support watch/multi/exec commands

**Comment by eyjian** [comment]
can support watch/multi/exec commands with the same key or hash tag, like following:
10.225.168.252:6380> MULTI
OK
10.225.168.252:6380> incr f
QUEUED
10.225.168.252:6380> incr f
QUEUED
10.225.168.252:6380> exec
1) (integer) 3
2) (integer) 4
10.225.168.252:6380> get f
"4"
10.225.168.252:6380> del f
(integer) 1
10.225.168.252:6380> MULTI
OK
10.225.168.252:6380> incr {f}_1
QUEUED
10.225.168.252:6380> incr {f}_2
QUEUED
10.225.168.252:6380> exec
1) (integer) 1
2) (integer) 1
10.225.168.252:6380> get {f}_1
"1"
10.225.168.252:6380> get {f}_2
"1"

**Comment by eyjian** [comment]
add partial eval to support incrby with timeout

**Comment by ciasom** [comment]
+1  for transaction related commands

**Comment by eyjian** [comment]
support multi & exec now.

**Comment by jovan-wong** [comment]
+1

**Comment by eyjian** [comment]
https://redis.io/topics/transactions（末尾）
根据官方的说明，最好使用LUA替代MULTI+EXEC，性能更好，将来可能会废弃MULTI+EXEC方式的事物。
