### ISSUE TITLE
CRedisClient 有没有断开重连的机制？ 我测试了一下好像没有。

### ISSUE THREAD

**Issue by sunnyyellow** [eyjian/r3c#22]

**Comment by eyjian** [comment]
断开会重连接，请问你是怎么测试的？

**Comment by eyjian** [comment]
单机模式下存在连接断开不能重连接问题，已修复。
https://github.com/eyjian/r3c/commit/2c509065b313b5be7a356da4b114a1dd938ae6e5

**Comment by eyjian** [comment]
单机模式确实存在问题，今天做了修复。
