### ISSUE TITLE
[bug] 集群模式下循环尝试链接时，connect_redis_node 传进去的errorinfo没有清空

### ISSUE THREAD

**Issue by sunnyyellow** [eyjian/r3c#23]
场景描述：
集群模式下，设置密码。如果一个主节点异常，从节点转换为主节点。 
调用构造函数时，节点信息传入的是原始的主节点信息。
此时循环尝试连接节点时，如果第一次连接到坏掉的节点，连接的异常信息会保存在errorinfo里面。

在第二次连接时，errorinfo信息被传入connect_redis_node()。上次失败的errorinfo信息没有被清空，会影响本次连接时的AUTH验证。 触发 NOAUTH Authentication required 的异常。

**Comment by eyjian** [comment]
谢谢发现问题，已经修复。时间拖久了点，抱歉！
