### ISSUE TITLE
Can you enable support for LSET,LPUSH,LRANGE ..?

### ISSUE THREAD

**Issue by sekarpdkt** [eyjian/r3c#31]
Hi Will you be able to enable it for LSET, LPUSH ,LDEL, LRANGE...? Basically new sets of list command support.

**Comment by eyjian** [comment]
LSET, LINDEX, LREM, LINSERT and LPUSHX added now.

**Comment by sekarpdkt** [comment]
hi Thank you very much. I will check it.
