### ISSUE TITLE
C++17 support and some issue in make

### ISSUE THREAD

**Issue by sekarpdkt** [eyjian/r3c#33]
hi

1. Will you be able to support C++17. Primarily dynamic exception specifications like `throw (CRedisException);` are no more supported.

2. When I do make, 
```
/usr/bin/c++  -g  -rdynamic CMakeFiles/r3c_test.dir/r3c_test.cpp.o  -o r3c_test  -L/r3c  -L/r3c/HIREDIS_LIB-NOTFOUND -Wl,-rpath,/r3c:/r3c/HIREDIS_LIB-NOTFOUND -Wl,-Bstatic -lr3c -lhiredis -Wl,-Bdynamic
```
fails with error `/usr/bin/ld: cannot find -lhiredis`

If I remove extra `-Wl,` before `-Bstatic,` it works. Mean

```
/usr/bin/c++  -g  -rdynamic CMakeFiles/r3c_test.dir/r3c_test.cpp.o  -o r3c_test  -L/r3c  -L/r3c/HIREDIS_LIB-NOTFOUND -Wl,-rpath,/r3c:/r3c/HIREDIS_LIB-NOTFOUND  -Bstatic -lr3c -lhiredis -Wl,-Bdynamic
```
works.

**Comment by eyjian** [comment]
No problem, I will test it on C++ 17 (Current) and fix make.

**Comment by eyjian** [comment]
1. All dynamic exception specifications have been removed.
2. The link error is becase cmake can not find the hiredis,  you can specify hiredis by cmake's parameter -D, for example:
cmake -DHIREDIS=/usr/local/hiredis .
cmake will find hiredis in these directrories: /usr/local/hiredis, /usr/local

**Comment by sekarpdkt** [comment]
Thanks. I also created a dockerfile to compile. Also a simple make file to compile it externally for users who want to try it quickly. If ok, I will send a PR with engling readme.RD. Let me know.

We can close this issue. Thanks.

**Comment by eyjian** [comment]
Thank you, my English is poor.

**Comment by sekarpdkt** [comment]
Closing it. Submit PR by week end.
