### ISSUE TITLE
Do you have connection pool support?

### ISSUE THREAD

**Issue by sekarpdkt** [eyjian/r3c#35]
Do you have any example with connection pool?

**Comment by sekarpdkt** [comment]
I did some changes and came up with this approach. Do you have any comment or better ideas? It this case I have spanned fixed number of threads. From main thread distributing load to threads thru message queue. Basic idea is to keep pools connected with redis ready.

Ideally I would have liked to keep threadpool but could not find better alternatives.


[Makefile.txt](https://github.com/eyjian/r3c/files/3133988/Makefile.txt)
[redisClient.cpp.txt](https://github.com/eyjian/r3c/files/3133989/redisClient.cpp.txt)

**Comment by eyjian** [comment]
Like this? I don't know where the connection pool is used.
![image](https://user-images.githubusercontent.com/4222271/57204943-8fae2e00-6fed-11e9-9c03-6affa9506d66.png)

**Comment by sekarpdkt** [comment]
Yes. Something like above.
