### ISSUE TITLE
about hset return value

### ISSUE THREAD

**Issue by hd86** [eyjian/r3c#8]
else if (REDIS_REPLY_INTEGER == redis_reply->type)
 {
    **result** = redis_reply->integer;
}

bool CRedisClient::hset(const std::string& key, const std::string& field, const std::string& value, std::pair<std::string, uint16_t>* which) throw (CRedisException)
{
    struct ParamInfo param_info("HSET", sizeof("HSET")-1, &key, which);
    param_info.str1 = &field;
    param_info.str2 = &value;
    int64_t result = redis_command(REDIS_REPLY_INTEGER, &param_info);
    return **result** > 0;
}

When the value set by hset is written repeatedly, redis_reply-> integer returns the value 0.
so hset will return false.

当hset重复存入的value时，  redis_reply-> integer 返回值是0。
会导致hset 函数中 关于 大于0的判断 返回 false。 这里是不是应该改为 >=0 ,或者 修改为 返回int类型

**Comment by eyjian** [comment]
hset返回true表示第一次设置该field，返回false表示重复设置该field。如果改成>=0，那总是返回true了，如果是出错，则抛出异常。

**Comment by hd86** [comment]
返回false表示重复设置？ 那hset不成功 要自己catch异常？

**Comment by hd86** [comment]
就是 true 代表 第一次设置成功。 false 表示重复设置。 异常 要自己catch处理？

**Comment by eyjian** [comment]
对，异常需要自己catch的，当前正是第一次返回true，之后返回false，你测试的不是这样吗？

**Comment by hd86** [comment]
正事测试的时候发现日志中总打印出 failed 但是数据还成功更新了。可能我习惯的C语言的错误的紧耦合处理方式。

**Comment by hd86** [comment]
正是测试的时候发现日志中总打印出 failed 但是数据还成功更新了。可能我习惯的C语言的错误的紧耦合处理方式。会觉得这样怪怪的

**Comment by eyjian** [comment]
你是把false当作hset失败了，实际它只是表示是第一次还是非第一次hset目标字段，出错是异常方式。

**Comment by eyjian** [comment]
加了个简单注释，希望对使用有帮助，不然确实会误导

**Comment by eyjian** [comment]
当前对timeout不重试，对于读理论上可以重试，但对于写则不能，因为超时有可能是成功也可能是失败

**Comment by hd86** [comment]
：)。那使用时 我就不判断返回值 直接catch异常吧。
